version: 0.2

phases:
  install:
    commands:
      - echo "fetching files"
      - echo $(which go)
      - go get -u ./...
  build:
    commands:
      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
