version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - go get -u ./...
  build:
    commands:
      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
