version: 0.1

phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
