version: 0.2

env:
  variables:
    GO111MODULE: "on"
    git-credential-helper: y

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo GOPATH - $GOPATH
      - go get -u ./...
  build:
    commands:
      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
